/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.a.demirbas;

import java.awt.LayoutManager;
import java.awt.image.BufferedImage;
import java.beans.PropertyChangeEvent;
import java.beans.Statement;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author w10
 */
public class LoginFrame extends javax.swing.JFrame {

    HashMap<String, String> imageList;
    DefaultListModel lstImagesDefaultListModel;
    DefaultListModel lst_logModel;

    public LoginFrame() {
        initComponents();
        lstImagesDefaultListModel = new DefaultListModel();
        lst_images.setModel(lstImagesDefaultListModel); //olusturulan defaultListModel imageslari tutan listeye set edildi

       

        String imageFolderPath = this.getClass().getClassLoader().getResource("images").getFile(); //imagelarin path adresi String bir degiskende tutuldu.
        File file = new File(imageFolderPath); // File objesi olusturularak bu adres file icine atandi
        File[] files = file.listFiles(); //File dizisi olusturuldu, imagelar artik file icinde, filedaki imagelari listeye atmamiz gerekiyor

        imageList = new HashMap<>(); //imageList objesi HashMap anahtar kelimesiyle olusturuldu

        for (File item : files) { //File listesi icinde item ile geziyor
            imageList.put(item.getName(), item.getAbsolutePath()); //onceden olusturdugumuz imageListe(HashMap) Filedaki imagelar eklendi, adresleri ile beraber
            lstImagesDefaultListModel.addElement(item.getName()); //jliste default olarak set ettigimiz liste bu itemi ekliyoruz
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnl_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nameSurname = new javax.swing.JTextField();
        password_area = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        pnl_listOfImages = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_images = new javax.swing.JList<>();
        pnl_images = new javax.swing.JPanel();
        lbl_images = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(733, 550));
        setPreferredSize(new java.awt.Dimension(900, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(733, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(733, 550));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        pnl_login.setBackground(new java.awt.Color(152, 180, 194));
        pnl_login.setForeground(new java.awt.Color(0, 51, 51));
        pnl_login.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnl_login.setMinimumSize(new java.awt.Dimension(733, 550));
        pnl_login.setName(""); // NOI18N
        pnl_login.setPreferredSize(new java.awt.Dimension(733, 550));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("FATIH SULTAN MEHMET VAKIF UNIVERSITY");

        jLabel2.setBackground(new java.awt.Color(51, 0, 102));
        jLabel2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 95, 120));
        jLabel2.setText("FIXTURE and STOCK SITUATION");

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(59, 88, 116));
        jLabel3.setText("LOGIN PAGE");

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 72, 164));
        jLabel4.setText("Name-Surname:");

        jLabel7.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(72, 72, 183));
        jLabel7.setText("PASSWORD:");

        btn_login.setBackground(new java.awt.Color(255, 255, 255));
        btn_login.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(0, 0, 102));
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(48, 92, 121));
        jLabel6.setText("FACULTY OF ENGINEERING");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\w10\\Documents\\NetBeansProjects\\A-DEMIRBAS\\src\\main\\java\\loginImages\\fsmvuLogo.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\w10\\Documents\\NetBeansProjects\\A-DEMIRBAS\\src\\main\\java\\loginImages\\person2.png")); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\w10\\Documents\\NetBeansProjects\\A-DEMIRBAS\\src\\main\\java\\loginImages\\password_son.png")); // NOI18N

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_loginLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_loginLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(52, 52, 52)
                                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password_area, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_area, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel1.add(pnl_login);

        jTabbedPane1.addTab("LOGIN PAGE", jPanel1);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        pnl_listOfImages.setMinimumSize(new java.awt.Dimension(100, 200));
        pnl_listOfImages.setPreferredSize(new java.awt.Dimension(100, 200));
        pnl_listOfImages.setLayout(new javax.swing.BoxLayout(pnl_listOfImages, javax.swing.BoxLayout.LINE_AXIS));

        lst_images.setBackground(new java.awt.Color(196, 218, 233));
        lst_images.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_imagesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lst_images);

        pnl_listOfImages.add(jScrollPane1);

        jSplitPane2.setLeftComponent(pnl_listOfImages);

        pnl_images.setBackground(new java.awt.Color(217, 233, 248));
        pnl_images.setMinimumSize(new java.awt.Dimension(300, 300));
        pnl_images.setPreferredSize(new java.awt.Dimension(200, 200));
        pnl_images.setLayout(new javax.swing.BoxLayout(pnl_images, javax.swing.BoxLayout.LINE_AXIS));

        lbl_images.setBackground(new java.awt.Color(0, 51, 0));
        pnl_images.add(lbl_images);
        pnl_images.add(jLabel10);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\w10\\Documents\\NetBeansProjects\\A-DEMIRBAS\\src\\main\\java\\loginImages\\logo_1.png")); // NOI18N
        pnl_images.add(jLabel11);

        jSplitPane2.setRightComponent(pnl_images);

        jSplitPane1.setRightComponent(jSplitPane2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea1.setBackground(new java.awt.Color(160, 184, 207));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("     Fatih Sultan Mehmet Vakıf University (FSMVU) is a newly established higher education institute whose goal is to be at the forefront of Turkish higher education and research. The university is subsidized by a very special charity (waqf), the Fatih Sultan Mehmet Charity which was founded in 1470 to facilitate education and continues to serve this goal for over five centuries. FSMVU emerged from the historical waqf tradition which played an influential role in the scientific, civic, and cultural life throughout Ottoman history. Being privileged to have its origins in the centuries old civic and academic heritage, FSMVU strives to carry on this tradition by combining traditional education with contemporary knowledge.\n\n     FSMVU is located in the historical peninsula of Istanbul, which lies at the heart of the city where culture, history and art are parts of the fabric of everyday life. Our location lends a unique quality to our academic vision. FSMVU hosts all members of the higher education community, from faculty members and researchers, to graduate and undergraduate students.");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2);

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.add(jSplitPane1);

        jTabbedPane1.addTab("ABOUT", jPanel3);

        getContentPane().add(jTabbedPane1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        String nameSurname = txt_nameSurname.getText(); 
        String password = password_area.getText();
        try {
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/DemirbasDB;user=sa;password=as"); //Connection conn olusturarak olusturdugumuz database'in adresini girdim
            String sql = "SELECT * FROM FSMVU_LOGIN WHERE NAMESURNAME=? AND PASSWORD=?"; //SELECT commanti ile kullanicinin girdigi isim ve soyismi databaseden sectim
            PreparedStatement pst = conn.prepareStatement(sql); //Önceden derlenmiş bir SQL ifadesini temsil eden bir nesne olusturdum.
//derledigim sql ifadesini daha sonra da kullanabilmek icin PreparedStatement nesnesinde sakladim.
            pst.setString(1, nameSurname); //kullanicinin girecegi name/surname/password bilgilerini icinde tuttum
            pst.setString(2, password);
            ResultSet rs = pst.executeQuery(); //resultset ile veritabanini sorguladim

            if (rs.next()) { //eger uyusuyor ise
                JOptionPane.showMessageDialog(rootPane, "INFOS MATCHED"); //JOptionPane ile mesaji verdim
                ControlFrame controlFrame = new ControlFrame(); //Control frame'i actim
                controlFrame.setVisible(true);//gorunurlugunu true yaptim ki acildiginda ekranda gorebileyim
                this.dispose(); //login ekranini kapattim

            } else { //uyusmuyor ise
                JOptionPane.showMessageDialog(rootPane, "INFOS ARENT MATCHED!"); //JOptionPane ile hata mesaji verdirdim.
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void lst_imagesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_imagesValueChanged

        String value = lst_images.getSelectedValue(); //fotograf listesinde secilen valueyu String degiskende tuttuk
        String path = imageList.get(value); //secilen valuenun adresini yine string degikende tuttuk
        ImageIcon icon = new ImageIcon(path); //fotografin pathini bir icon objesinde olusturduk
        lbl_images.setIcon(icon); //labela bu iconu set ettik

    }//GEN-LAST:event_lst_imagesValueChanged

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_images;
    private javax.swing.JList<String> lst_images;
    private javax.swing.JPasswordField password_area;
    private javax.swing.JPanel pnl_images;
    private javax.swing.JPanel pnl_listOfImages;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JTextField txt_nameSurname;
    // End of variables declaration//GEN-END:variables
}
